// Generated by tools/generate_extension.py. Do not edit.
globalThis.CloudDeskCatalog = {
  "basic": [
    {
      "scope": [
        "Zone",
        "区域"
      ],
      "names": [
        "DNS"
      ],
      "access": [
        "Edit",
        "编辑"
      ],
      "title": "DNS 增删改 / 替换 / 代理"
    },
    {
      "scope": [
        "Zone",
        "区域"
      ],
      "names": [
        "Zone",
        "区域",
        "区域 Zone"
      ],
      "access": [
        "Edit",
        "编辑"
      ],
      "title": "添加 / 删除域名"
    },
    {
      "scope": [
        "Zone",
        "区域"
      ],
      "names": [
        "Zone Settings",
        "区域设置"
      ],
      "access": [
        "Edit",
        "编辑"
      ],
      "title": "SSL/TLS / 缓存配置 / 优化 / 其他设置"
    },
    {
      "scope": [
        "Zone",
        "区域"
      ],
      "names": [
        "Cache Purge",
        "清除缓存"
      ],
      "access": [
        "Purge",
        "清除"
      ],
      "title": "清除缓存"
    },
    {
      "scope": [
        "Zone",
        "区域"
      ],
      "names": [
        "SSL and Certificates",
        "SSL 和证书",
        "SSL及证书"
      ],
      "access": [
        "Edit",
        "编辑"
      ],
      "title": "SSL 自定义主机名"
    },
    {
      "scope": [
        "Zone",
        "区域"
      ],
      "names": [
        "Page Rules",
        "页面规则"
      ],
      "access": [
        "Edit",
        "编辑"
      ],
      "title": "页面规则"
    }
  ],
  "full": [
    {
      "scope": [
        "Zone",
        "区域"
      ],
      "names": [
        "DNS"
      ],
      "access": [
        "Edit",
        "编辑"
      ],
      "title": "DNS 增删改 / 替换 / 代理"
    },
    {
      "scope": [
        "Zone",
        "区域"
      ],
      "names": [
        "Zone",
        "区域",
        "区域 Zone"
      ],
      "access": [
        "Edit",
        "编辑"
      ],
      "title": "添加 / 删除域名"
    },
    {
      "scope": [
        "Zone",
        "区域"
      ],
      "names": [
        "Zone Settings",
        "区域设置"
      ],
      "access": [
        "Edit",
        "编辑"
      ],
      "title": "SSL/TLS / 缓存配置 / 优化 / 其他设置"
    },
    {
      "scope": [
        "Zone",
        "区域"
      ],
      "names": [
        "Cache Purge",
        "清除缓存"
      ],
      "access": [
        "Purge",
        "清除"
      ],
      "title": "清除缓存"
    },
    {
      "scope": [
        "Zone",
        "区域"
      ],
      "names": [
        "SSL and Certificates",
        "SSL 和证书",
        "SSL及证书"
      ],
      "access": [
        "Edit",
        "编辑"
      ],
      "title": "SSL 自定义主机名"
    },
    {
      "scope": [
        "Zone",
        "区域"
      ],
      "names": [
        "Page Rules",
        "页面规则"
      ],
      "access": [
        "Edit",
        "编辑"
      ],
      "title": "页面规则"
    },
    {
      "scope": [
        "Zone",
        "区域"
      ],
      "names": [
        "Zone WAF",
        "区域 WAF"
      ],
      "access": [
        "Edit",
        "编辑"
      ],
      "title": "WAF 自定义规则"
    },
    {
      "scope": [
        "Zone",
        "区域"
      ],
      "names": [
        "Cache Rules",
        "缓存规则",
        "Cache Settings",
        "缓存设置"
      ],
      "access": [
        "Edit",
        "编辑"
      ],
      "title": "缓存规则"
    },
    {
      "scope": [
        "Zone",
        "区域"
      ],
      "names": [
        "Transform Rules",
        "转换规则",
        "Zone Transform Rules",
        "区域转换规则"
      ],
      "access": [
        "Edit",
        "编辑"
      ],
      "title": "重写 URL"
    },
    {
      "scope": [
        "Zone",
        "区域"
      ],
      "names": [
        "Single Redirect",
        "单一重定向",
        "单个重定向",
        "Dynamic URL Redirects",
        "动态 URL 重定向"
      ],
      "access": [
        "Edit",
        "编辑"
      ],
      "title": "重定向规则"
    },
    {
      "scope": [
        "Zone",
        "区域"
      ],
      "names": [
        "Origin Rules",
        "源站规则",
        "Origin",
        "源站"
      ],
      "access": [
        "Edit",
        "编辑"
      ],
      "title": "源站规则"
    },
    {
      "scope": [
        "Zone",
        "区域"
      ],
      "names": [
        "Config Rules",
        "配置规则",
        "Config Settings",
        "配置设置"
      ],
      "access": [
        "Edit",
        "编辑"
      ],
      "title": "配置规则"
    },
    {
      "scope": [
        "Zone",
        "区域"
      ],
      "names": [
        "Response Compression",
        "响应压缩"
      ],
      "access": [
        "Edit",
        "编辑"
      ],
      "title": "压缩规则"
    }
  ]
};
