"""Generate extension permission data from the app's single permission registry."""
import json
import sys
from dataclasses import asdict
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
from cloudtool.browser_token_model import BrowserTokenRequest
from cloudtool.permissions import PRESETS, RULE_PERMISSIONS

def catalog():
    return {mode:[asdict(row) for row in BrowserTokenRequest('CloudDesk',PRESETS['常用管理'],rules).permissions()]
            for mode,rules in (('basic',()),('full',tuple(RULE_PERMISSIONS)))}

if __name__=='__main__':
    (ROOT/'browser_extension/catalog.js').write_text('// Generated by tools/generate_extension.py. Do not edit.\nglobalThis.CloudDeskCatalog = '+json.dumps(catalog(),ensure_ascii=False,indent=2)+';\n','utf-8')
